import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Coordinate, Plot, Beacon, Project } from '@/types/survey';
import { formatArea, calculateArea, calculatePerimeter } from '@/lib/geometry';

interface ExportData {
  project: {
    name: string;
    clientName?: string;
    date: string;
  };
  parcel: {
    coordinates: Coordinate[];
    areaSqm: number;
    perimeterM: number;
  };
  plots: Plot[];
  beacons: Beacon[];
}

// Generate PDF mutation map and beacon list
export async function generatePDF(data: ExportData): Promise<Blob> {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  
  // Title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('MUTATION MAP', pageWidth / 2, 20, { align: 'center' });
  
  // Project info
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Project: ${data.project.name}`, 20, 35);
  if (data.project.clientName) {
    pdf.text(`Client: ${data.project.clientName}`, 20, 42);
  }
  pdf.text(`Date: ${data.project.date}`, 20, 49);
  
  // Parcel Summary
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('PARCEL SUMMARY', 20, 65);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Total Area: ${formatArea(data.parcel.areaSqm)}`, 20, 75);
  pdf.text(`Perimeter: ${data.parcel.perimeterM.toFixed(2)} m`, 20, 82);
  pdf.text(`Vertices: ${data.parcel.coordinates.length}`, 20, 89);
  pdf.text(`Total Plots: ${data.plots.length}`, 20, 96);
  pdf.text(`Total Beacons: ${data.beacons.length}`, 20, 103);
  
  // Parcel Coordinates Table
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('PARCEL BOUNDARY COORDINATES', 20, 120);
  
  const parcelCoordData = data.parcel.coordinates.map((coord, idx) => [
    `P${idx + 1}`,
    coord.lat.toFixed(8),
    coord.lng.toFixed(8),
  ]);
  
  autoTable(pdf, {
    startY: 125,
    head: [['Point', 'Latitude', 'Longitude']],
    body: parcelCoordData,
    theme: 'grid',
    headStyles: { fillColor: [0, 100, 80] },
    styles: { fontSize: 9, cellPadding: 2 },
  });
  
  // Plot Summary Table
  pdf.addPage();
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('PLOT SUMMARY', 20, 20);
  
  const plotData = data.plots.map(plot => [
    `Plot ${plot.plot_number}`,
    `${plot.area_sqm.toFixed(2)} m²`,
    plot.width_m ? `${plot.width_m.toFixed(2)} m` : '-',
    plot.depth_m ? `${plot.depth_m.toFixed(2)} m` : '-',
    plot.is_partial ? 'Yes' : 'No',
  ]);
  
  autoTable(pdf, {
    startY: 25,
    head: [['Plot', 'Area', 'Width', 'Depth', 'Partial']],
    body: plotData,
    theme: 'grid',
    headStyles: { fillColor: [0, 100, 80] },
    styles: { fontSize: 9, cellPadding: 2 },
  });
  
  // Beacon Coordinate List
  pdf.addPage();
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('BEACON COORDINATE LIST', 20, 20);
  
  const beaconData = data.beacons.map(beacon => [
    `B${beacon.beacon_number}`,
    beacon.latitude.toFixed(8),
    beacon.longitude.toFixed(8),
    beacon.description || '-',
  ]);
  
  autoTable(pdf, {
    startY: 25,
    head: [['Beacon', 'Latitude', 'Longitude', 'Description']],
    body: beaconData,
    theme: 'grid',
    headStyles: { fillColor: [0, 100, 80] },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 40 },
      2: { cellWidth: 40 },
      3: { cellWidth: 'auto' },
    },
  });
  
  // Individual Plot Details
  if (data.plots.length > 0 && data.plots.length <= 20) {
    pdf.addPage();
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('INDIVIDUAL PLOT COORDINATES', 20, 20);
    
    let yPos = 30;
    
    data.plots.forEach((plot, plotIdx) => {
      if (yPos > 260) {
        pdf.addPage();
        yPos = 20;
      }
      
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`Plot ${plot.plot_number} (${plot.area_sqm.toFixed(2)} m²)`, 20, yPos);
      yPos += 5;
      
      const plotCoords = plot.coordinates.map((coord, idx) => [
        `Corner ${idx + 1}`,
        coord.lat.toFixed(8),
        coord.lng.toFixed(8),
      ]);
      
      autoTable(pdf, {
        startY: yPos,
        head: [['Corner', 'Latitude', 'Longitude']],
        body: plotCoords,
        theme: 'grid',
        headStyles: { fillColor: [50, 50, 50] },
        styles: { fontSize: 8, cellPadding: 1 },
        margin: { left: 20 },
      });
      
      yPos = (pdf as any).lastAutoTable.finalY + 10;
    });
  }
  
  // Footer on all pages
  const pageCount = pdf.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text(
      `Generated by VipimoAI | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pdf.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  return pdf.output('blob');
}

// Generate GeoJSON export
export function generateGeoJSON(data: ExportData): string {
  const features: any[] = [];
  
  // Parent parcel polygon
  features.push({
    type: 'Feature',
    properties: {
      name: 'Parent Parcel',
      area_sqm: data.parcel.areaSqm,
      perimeter_m: data.parcel.perimeterM,
      type: 'parcel',
    },
    geometry: {
      type: 'Polygon',
      coordinates: [[
        ...data.parcel.coordinates.map(c => [c.lng, c.lat]),
        [data.parcel.coordinates[0].lng, data.parcel.coordinates[0].lat], // Close polygon
      ]],
    },
  });
  
  // Subdivision plots
  data.plots.forEach(plot => {
    features.push({
      type: 'Feature',
      properties: {
        name: `Plot ${plot.plot_number}`,
        plot_number: plot.plot_number,
        area_sqm: plot.area_sqm,
        width_m: plot.width_m,
        depth_m: plot.depth_m,
        is_partial: plot.is_partial,
        type: 'plot',
      },
      geometry: {
        type: 'Polygon',
        coordinates: [[
          ...plot.coordinates.map(c => [c.lng, c.lat]),
          [plot.coordinates[0].lng, plot.coordinates[0].lat],
        ]],
      },
    });
  });
  
  // Beacons as points
  data.beacons.forEach(beacon => {
    features.push({
      type: 'Feature',
      properties: {
        name: `Beacon ${beacon.beacon_number}`,
        beacon_number: beacon.beacon_number,
        description: beacon.description,
        type: 'beacon',
      },
      geometry: {
        type: 'Point',
        coordinates: [beacon.longitude, beacon.latitude],
      },
    });
  });
  
  const geojson = {
    type: 'FeatureCollection',
    name: data.project.name,
    crs: {
      type: 'name',
      properties: {
        name: 'urn:ogc:def:crs:OGC:1.3:CRS84',
      },
    },
    features,
  };
  
  return JSON.stringify(geojson, null, 2);
}

// Generate KML export
export function generateKML(data: ExportData): string {
  const coordsToKML = (coords: Coordinate[]): string => {
    return coords.map(c => `${c.lng},${c.lat},0`).join(' ');
  };
  
  let placemarks = '';
  
  // Parent parcel
  const parcelCoords = coordsToKML([...data.parcel.coordinates, data.parcel.coordinates[0]]);
  placemarks += `
    <Placemark>
      <name>Parent Parcel</name>
      <description>
        Area: ${formatArea(data.parcel.areaSqm)}
        Perimeter: ${data.parcel.perimeterM.toFixed(2)} m
      </description>
      <Style>
        <LineStyle>
          <color>ff0000ff</color>
          <width>3</width>
        </LineStyle>
        <PolyStyle>
          <color>400000ff</color>
        </PolyStyle>
      </Style>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>${parcelCoords}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>`;
  
  // Plots folder
  placemarks += `
    <Folder>
      <name>Plots</name>`;
  
  data.plots.forEach(plot => {
    const plotCoords = coordsToKML([...plot.coordinates, plot.coordinates[0]]);
    placemarks += `
      <Placemark>
        <name>Plot ${plot.plot_number}</name>
        <description>
          Area: ${plot.area_sqm.toFixed(2)} m²
          Width: ${plot.width_m?.toFixed(2) || '-'} m
          Depth: ${plot.depth_m?.toFixed(2) || '-'} m
        </description>
        <Style>
          <LineStyle>
            <color>ff00ff00</color>
            <width>2</width>
          </LineStyle>
          <PolyStyle>
            <color>4000ff00</color>
          </PolyStyle>
        </Style>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>${plotCoords}</coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
      </Placemark>`;
  });
  
  placemarks += `
    </Folder>`;
  
  // Beacons folder
  placemarks += `
    <Folder>
      <name>Beacons</name>`;
  
  data.beacons.forEach(beacon => {
    placemarks += `
      <Placemark>
        <name>B${beacon.beacon_number}</name>
        <description>${beacon.description || ''}</description>
        <Style>
          <IconStyle>
            <color>ff00d4aa</color>
            <scale>0.8</scale>
            <Icon>
              <href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href>
            </Icon>
          </IconStyle>
        </Style>
        <Point>
          <coordinates>${beacon.longitude},${beacon.latitude},0</coordinates>
        </Point>
      </Placemark>`;
  });
  
  placemarks += `
    </Folder>`;
  
  const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${data.project.name}</name>
    <description>Subdivision export - ${data.project.clientName || 'No client'}</description>
    ${placemarks}
  </Document>
</kml>`;
  
  return kml;
}

// Generate CSV beacon list
export function generateBeaconCSV(data: ExportData): string {
  let csv = 'Beacon,Latitude,Longitude,Description\n';
  
  data.beacons.forEach(beacon => {
    csv += `B${beacon.beacon_number},${beacon.latitude.toFixed(8)},${beacon.longitude.toFixed(8)},"${beacon.description || ''}"\n`;
  });
  
  return csv;
}

// Download helper
export function downloadFile(content: Blob | string, filename: string, mimeType?: string) {
  const blob = content instanceof Blob
    ? content
    : new Blob([content], { type: mimeType || 'text/plain' });
  
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
