# Generated by Django 5.0.14 on 2026-06-22 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plot_number', models.IntegerField()),
                ('coordinates', models.JSONField()),
                ('area_sqm', models.DecimalField(decimal_places=4, max_digits=18)),
                ('width_m', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('depth_m', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_partial', models.BooleanField(default=False)),
                ('status', models.CharField(default='valid', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beacon_number', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('easting', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('northing', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacons', to='core.plot')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_area_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='core.project'),
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Parent Parcel', max_length=255)),
                ('coordinates', models.JSONField()),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('perimeter_m', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('centroid', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(max_length=50)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('action_label', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plot_width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('plot_depth', models.DecimalField(decimal_places=4, max_digits=10)),
                ('target_plot_count', models.IntegerField(blank=True, null=True)),
                ('strategy', models.CharField(choices=[('auto_fit', 'Auto Fit'), ('fixed_count', 'Fixed Count'), ('equal_resize', 'Equal Resize'), ('extract_full', 'Extract Full')], default='auto_fit', max_length=20)),
                ('orientation_degrees', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('road_setback_m', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('side_setback_m', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ai_suggestions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='core.parcel')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='core.subdivision'),
        ),
    ]
