# Generated by Django 5.0.14 on 2026-06-23 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RIMRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024)),
                ('preview_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('crs', models.CharField(default='EPSG:21037', max_length=50)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('transform', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RIMExtractedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('rim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='spatial_db.rimraster')),
            ],
        ),
        migrations.CreateModel(
            name='TruthOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_project', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', models.JSONField()),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('immutable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='spatial_db.rimraster')),
            ],
        ),
    ]
