# Generated by Django 5.0.14 on 2026-06-23 20:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rimextractedfeature',
            name='geometry_spatial',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=21037),
        ),
        migrations.AddField(
            model_name='rimraster',
            name='footprint',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=21037),
        ),
        migrations.AddField(
            model_name='truthoverride',
            name='geometry_spatial',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=21037),
        ),
    ]
